import { SCOUT_OUTCOMES, SCOUT_STATUS_BY_OUTCOME } from "./scout.mjs";
import { DECOMPOSE_STATUS_BY_OUTCOME } from "./decompose.mjs";

export const OUTCOMES = Object.freeze({
  WORKER_DONE: "WORKER_DONE",
  WORKER_PARTIAL: "WORKER_PARTIAL",
  WORKER_BLOCKED: "WORKER_BLOCKED",
  WORKER_REPORT_INVALID: "WORKER_REPORT_INVALID",
  WORKER_TIMEOUT: "WORKER_TIMEOUT",
  WORKER_FAILED: "WORKER_FAILED",
  RECOVERED_SUCCESS: "RECOVERED_SUCCESS",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  ...SCOUT_OUTCOMES
});

export const COORDINATOR_STATUS_BY_OUTCOME = Object.freeze({
  [OUTCOMES.WORKER_DONE]: "complete",
  [OUTCOMES.RECOVERED_SUCCESS]: "complete",
  [OUTCOMES.WORKER_BLOCKED]: "blocked",
  [OUTCOMES.NEEDS_REVIEW]: "needs_review",
  [OUTCOMES.WORKER_PARTIAL]: "incomplete",
  [OUTCOMES.WORKER_REPORT_INVALID]: "incomplete",
  [OUTCOMES.WORKER_TIMEOUT]: "incomplete",
  [OUTCOMES.WORKER_FAILED]: "failed",
  ...SCOUT_STATUS_BY_OUTCOME,
  ...DECOMPOSE_STATUS_BY_OUTCOME
});
